[context.production.environment]
  HUGO_VERSION = "0.71.1"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.71.1"

[build]
  base = ""
  publish = "public"
  command = "hugo"
  functions = "functions"