---
label: Meta
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: textarea
  name: description
  label: description
- type: file
  name: image
  label: image
- type: list
  name: keywords
  label: keywords
- type: boolean
  name: isHome
  label: isHome
- type: boolean
  name: carousel
  label: carousel
